# Generated by Django 3.1.1 on 2020-10-03 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('company_name', models.CharField(max_length=40)),
                ('last_price', models.IntegerField(default=0)),
                ('H_52_wk', models.IntegerField(default=0)),
                ('L_52_wk', models.IntegerField(default=0)),
                ('market_cap', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
